import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import { Toaster } from 'sonner'
import { ErrorHandler } from '@/components/ErrorHandler'
import { Suspense } from 'react'
import { auth } from '@/lib/features/auth/oAuth/auth'
import { SessionSynchronizer } from '@/components/SessionSyncer'
const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Gechis',
  description: 'Generated by create next app',
  icons: {
    icon: '/logo.svg',
  },
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en' data-lt-installed suppressHydrationWarning>
      <body
        suppressHydrationWarning
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Suspense>
          <ErrorHandler />
        </Suspense>
        <Toaster />
        <SessionSynchronizer>{children}</SessionSynchronizer>
      </body>
    </html>
  )
}
